// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvzvkrbreptwfrqaiyrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2enZrcmJyZXB0d2ZycWFpeXJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NTY4NDAsImV4cCI6MjA3MTUzMjg0MH0.HoHqLdUcejWdFD_VWfSelNoHKfXLr3stsLJatGTY-Hk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});